language: python

python:
  - 3.6

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=csinfo.settings
  - export PYTHONPATH=$HOME/builds/hcrudolph/ciphersuite.info
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py migrate auth
  - python manage.py migrate

script:
  - python manage.py test
